### ISSUE TITLE
not find code about line-detect

### ISSUE THREAD

**Issue by pkuswg** [somaveszelovszki/babocar-line-detector-firmware#1]
hello, i cant find the code about line-detect

**Comment by somaveszelovszki** [comment]
Hi,
Yes, the code is not available yet.
I will only start working on this repo in a few weeks, and I'm planning to finish it by June.
Come back in a few months and see if there's anything helpful in it for you.
Soma

**Comment by pkuswg** [comment]
OK,THANKS

**Comment by somaveszelovszki** [comment]
You can see it now
